exp_name:
  - socialforce

user_name:
  Yuzihan

# desired_speed:
#   - 1.34
# This argument is useless, as desired speed is set to max(0.8, sqrt(0.1) * N + 1.14), N ~ Gauss(0, 1)

desired_speed_intensity:
# 1.75
  2.00
# 2.50

pedped_repulsive_intensity:
# 3.1
  3.3
# 3.5

pedped_repulsive_radius:
# 0.3
  0.4
# 0.5

pedobs_repulsive_intensity:
  10

pedobs_repulsive_radius:
  0.2

oversampling:
  10

max_speed_multiplier:
# 1.3
  1.4
# 1.5

sight_angle_ped:
  90

seed:
  - 666
  - 777
  - 888

model:
  'socialforce'

visualization:
  1

scene:
  2

length:
  20

width:
  10

duration:
  60

save_path:
  # ./cache/
  '/data/zhangguozhen/dataset/pedsim/synthetic_data/social_force/'
