train:
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time2104-2164_interp9_xrange5-25_yrange15-35_simulation_7qitpmvy_iter0.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time2164-2224_interp9_xrange5-25_yrange15-35_simulation_7qitpmvy_iter0.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time2224-2284_interp9_xrange5-25_yrange15-35_simulation_7qitpmvy_iter0.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time2284-2344_interp9_xrange5-25_yrange15-35_simulation_7qitpmvy_iter0.npy'

valid:
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time2344-2404_interp9_xrange5-25_yrange15-35_simulation_7qitpmvy_iter0.npy'
