train:
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time760-820_interp9_xrange5-25_yrange15-35_simulation.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time1000-1060_interp9_xrange5-25_yrange15-35_simulation.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time1100-1160_interp9_xrange5-25_yrange15-35_simulation.npy'
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time1280-1340_interp9_xrange5-25_yrange15-35_simulation.npy'

valid:
  - '../data/synthetic_data/GC_Dataset_ped1-12685_time1560-1620_interp9_xrange5-25_yrange15-35_simulation.npy'