vis:
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time760-820_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time1000-1060_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time1100-1160_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time1280-1340_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time1560-1620_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time2224-2284_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time2344-2404_interp9_xrange5-25_yrange15-35.npy'
#  - '../data/synthetic_data/basic_unit2_seed777_20.0x10.0m_60.0s.npy'
#  - '../data/synthetic_data/basic_unit3_seed666_20.0x10.0m_60.0s.npy'
#  - '../data/synthetic_data/basic_unit3_seed777_20.0x10.0m_60.0s.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time2284-2344_interp9_xrange5-25_yrange15-35.npy'
  - '../data/synthetic_data/basic_unit2_seed666_20.0x10.0m_60.0s.npy'
