train:
  - '../data/synthetic_data/UCY_Dataset_time0-54_timeunit0.08_simulation.npy'
  - '../data/synthetic_data/UCY_Dataset_time54-108_timeunit0.08_simulation.npy'
  - '../data/synthetic_data/UCY_Dataset_time108-162_timeunit0.08_simulation.npy'

valid:
  - '../data/synthetic_data/UCY_Dataset_time162-216_timeunit0.08_simulation.npy'