train:
  - '../data/GC_dataset/GC_Dataset_toy1.npy'
#  - '../data/UCY_dataset/UCY_Dataset_time0-54_timeunit0.08.npy'
#  - '../data/GC_dataset/GC_Dataset_toy2.npy'
#  - '../data/GC_dataset/GC_Dataset_toy3.npy'

valid:
  - '../data/GC_dataset/GC_Dataset_toy4.npy'

test:
  - '../data/GC_dataset/GC_Dataset_toy5.npy'
#  - '../data/GC_dataset/GC_Dataset_ped1-12685_time760-820_interp9_xrange5-25_yrange15-35.npy'